### ISSUE TITLE
Random mods crash when this mod is present

### ISSUE THREAD

**Issue by vico93** [lamaprogramer/ReimaginedMenus#11]
Basically, after i've installed the 1.0.3-1.20.x version on my 1.20.1 modpack, it stopped working.

First, [the crash report](https://gist.github.com/vico93/06bd3df60c2406d06f26cdd6d3084b96) said it was an issue with [hang glider](https://github.com/Fuzss/hangglider) mod (i even created [a ticket](https://github.com/Fuzss/hangglider/issues/1) on their repository thinking it was its fault), then removing its jar the [crash](https://gist.github.com/vico93/71a1037e692b28d718a67918931ad991) "transfered" to puzzleslib, its dependency. Then i removed it, thinking it would finally solve any crash. But, for my surprise, now [it began](https://gist.github.com/vico93/c318fb5d684ce0371bdf85d1a6b1dfde) to accuse bedrockify as causing crashes, what i found strange since i didnt updated or change anything on that mod for a while.

So i started removing the mods i've added/updated most recently, one at the time, until i removed reimagined menus (that i had just added alongside a couple of others and updates). Booting the game without it ran fine, without errors.

**Comment by lamaprogramer** [comment]
How are you using Hangglider and Puzzleslib on 1.20.1? Those mods have only updated for 1.20 and won't even boot up for me on a 1.20.1 instance. In fact, over half your mods in the crash report have only updated to 1.20, and I even saw this: **"borderlessmining: Borderless Mining 1.1.7+1.19.4"** one which is on 1.19.4, how on earth did your game eve boot up??????

**Comment by lamaprogramer** [comment]
I also used my mod with Hangglider and puzzleslib on a 1.20 instance and it worked fine, it could be a problem with your mod versions, could you tell me what mods are on your instance now?

**Comment by vico93** [comment]
> I also used my mod with Hangglider and puzzleslib on a 1.20 instance and it worked fine, it could be a problem with your mod versions, could you tell me what mods are on your instance now, or maybe the ones you removed?

I can send my profile folder if you want. Do you have discord for me to send via PM?

**Comment by lamaprogramer** [comment]
yeh, I do, Iamaprogramer#2734

**Comment by Fuzss** [comment]
Hey there, this is caused by your `@Redirect` in `GameRendererMixin`. Using `@Redirect` generally isn't such a good idea, since it will fail if another mod also redirects the same method call, as is the case here (no clue which mod though, the crash report doesn't reveal that).

`@Redirect` can usually be replaced with a simple `@Inject` combined with cancelling the callback. So all you should need to do is swap your redirector with an injection at the head of `Lnet/minecraft/client/render/GameRenderer;updateWorldIcon()V` that is then cancelled.

It will no longer crash, but your world icon changes probably won't work for Vico as another mod seems to handle the world icon already (as indicated by it also redirecting the `updateWorldIcon` call).

**Comment by lamaprogramer** [comment]
@Fuzss, I see, thanks for the information, I’ll try and fix that real quick

**Comment by vico93** [comment]
> It will no longer crash, but your world icon changes probably won't work for Vico as another mod seems to handle the world icon already (as indicated by it also redirecting the `updateWorldIcon` call).

Yeah i currently use custom world icons for that functionality, but if reimagined menus also have this i will promptly remove that to use RM instead.

**Comment by lamaprogramer** [comment]
@vico93 @Fuzss, I think I fixed the crashes, let me know if you experience any more. PS (sorry it took a sec, life happened lol)
